spring:
  activemq:
    # ActiveMQ消息中间件服务器通讯地址
    broker-url: tcp://139.196.94.253:61616
    user: admin  # 用户名
    password: admin  #密码
  # 发送邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 邮箱用户名(邮件发送者)
    username: skwangxu@163.com
    # 授权码，163开通协议时设置的那个授权码，不是登录密码
    password: wx18227327313
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true

#自定义队列名属性，等下程序中会用到（以生产者的队列名一致）
queue: springboot-queue
server:
  port: 8081

